dist: trusty

language: c

compiler: gcc

sudo: required

before_install:
  - sudo apt-get update
  - chmod +x install-sw.sh

install: 
  - bash ./install-sw.sh

script: 
  - bash ./check_dependencies.sh
